# Generated by Django 4.2.23 on 2025-07-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='approved_limit',
            field=models.IntegerField(max_length=12),
        ),
        migrations.AlterField(
            model_name='customer',
            name='current_debt',
            field=models.IntegerField(default=0, max_length=12),
        ),
        migrations.AlterField(
            model_name='customer',
            name='monthly_salary',
            field=models.IntegerField(max_length=12),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_amount',
            field=models.IntegerField(max_length=12),
        ),
        migrations.AlterField(
            model_name='loan',
            name='monthly_repayment',
            field=models.IntegerField(max_length=12),
        ),
    ]
